path: /home/neo/Downloads/torchFlow/dataset
# change paths to the tiled dataset during training eg.
# /home/neo/Downloads/torchFlow/dataset for training on 3232 res.
# /home/neo/Downloads/torchFlow/dataset-1280 for training on 1280 res.
# /home/neo/Downloads/torchFlow/dataset-512 for training on 512 res.
# /home/neo/Downloads/torchFlow/dataset-256 for training on 256 res.
train: images/train
val: images/test

nc: 1
names:
  0: plastic
