# Validation arguments

data: config/dataset.yaml
imgsz: 3232 # [640, 480]
batch: 2
save_json: True
save_hybrid: False
conf: 0.15
iou: 0.3
max_det: 300
half: True
device: 0
dnn: False
plots: False
rect: False
split: val
