# Validation arguments

data: config/dataset.yaml
imgsz: 640 # (640, 480)
batch: 16
save_json: False
save_hybrid: False
conf: 0.001
iou: 0.6
max_det: 300
half: True
device: None
dnn: False
plots: False
rect: False
split: val